### PR TITLE
Add an optional message config parameter for warning and unassign messages so that they sound friendly

### PR DESCRIPTION
**Pull request by compwron**
https://github.com/rubyforgood/casa/issues/1589

### CODE REVIEW

**Comment by compwron** [comment]
hey @bjthompson805 I'm not sure this is exactly what one might want... but it's something I'd like to change up :) Feel free to edit / rewrite as needed if you want

**Comment by bjthompson805** [comment]
That seems good. I'll go ahead and merge.

**Comment by bjthompson805** [comment]
Hmm, I ran a test and it's not setting the default value of the parameter. Not sure why.

image

**Comment by bjthompson805** [comment]
You may need to set it on the CASA side (.github/workflows/issue-auto-unassign.yml)

**Pull request merged**
